packages:
  - chrome-extension
  - pages/content
  - pages/content-ui
  - pages/popup
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
